import type { Metadata } from "next";
import { Catamaran } from "next/font/google";
import "./globals.css";

import Navigation from "./components/navigation";
import Footer from "./components/footer";
import Header from "./components/header";

const catamaran = Catamaran({
  variable: "--font-catamaran",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${catamaran.className} antialiased bg-white`}>
        <main className="min-h-[calc(100dvh-45px)] w-screen max-w-6xl mx-auto lg:grid lg:grid-cols-4 gap-3 px-3 lg:px-1 pt-3">
          <Header />

          <section className="col-span-3">
            <Navigation />

            {children}
          </section>
        </main>

        <Footer />
      </body>
    </html>
  );
}
